linters-settings:
  gocyclo:
    min-complexity: 20
  govet:
    enable-all: true
  staticcheck:
    checks: ["all"]
linters:
  disable-all: true
  enable:
  - govet
  - staticcheck
  - unused
  - ineffassign
  - gocyclo
  - gosimple
  - errcheck
  - goimports
issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-dirs:
  - vendor
  exclude-rules:
  - path: "chacha20poly1305"
    text: "file requires newer Go version"
